ecommerce/cart/urls.py
from django.contrib import admin
from django.urls import path,include
from cart import views
app_name='cart'
urlpatterns = [
    path('add_to_cart/<int:b>/',views.add_to_cart,name="add_to_cart"),
    path('cartview', views.cartview, name="cartview"),
    path('cart_remove/<int:b>/',views.cart_remove,name="cart_remove"),
    path('cart_delete/<int:b>/',views.cart_delete,name="cart_delete"),
    path('orderform', views.orderform, name="orderform"),
    path('orderview', views.orderview, name="orderview"),

]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('search/', include('search.urls')),
    path('cart/', include('cart.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/search/urls.py
from django.contrib import admin
from django.urls import path
from search import views
app_name='search'
urlpatterns = [
    path('',views.searchresults,name="searchresults"),]

ecommerce/shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views
app_name='shop'
urlpatterns = [
    path('',views.allprodcat,name="allprodcat"),
    path('products/<slug:p>',views.allproducts,name="allproducts"),
    path('details/<slug:d>',views.details,name="details"),
    path('register', views.register, name="register"),
    path('login', views.user_login, name="login"),
    path('logout', views.user_logout, name="logout"),
]

ecommerce/cart/models.py
from django.db import models
from shop.models import Product
from django.contrib.auth.models import User

class Cart(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    date_added=models.DateField(auto_now_add=True)

    def subtotal(self):
        return self.quantity*self.product.price


    def __str__(self):
        return self.product.name

class Order(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    address=models.TextField()
    phone=models.CharField(max_length=100)
    order_status=models.CharField(max_length=30,default="pending")
    delivery_status=models.CharField(max_length=30,default="pending")
    noofitems=models.IntegerField()
    date_added=models.DateTimeField(auto_now_add=True)

    def subtotal(self):
        return self.noofitems * self.product.price

    def __str__(self):
            return self.user.username

class Account(models.Model):
    acctnumber=models.CharField(max_length=30)
    acctype=models.CharField(max_length=30)
    amount=models.IntegerField()
    def __str__(self):
        return self.acctnumber

ecommerce/search/models.py
from django.db import models

# Create your models here.

ecommerce/cart/views.py
from django.shortcuts import render,redirect
from shop.models import Product
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from cart.models import Cart,Account,Order

@login_required()
def cartview(request):
    total=0
    user=request.user
    try:
        cart=Cart.objects.filter(user=user)
        for i in cart:
            total+=i.quantity*i.product.price
    except Cart.DoesNotExist:
        pass
    return render(request,'cartview.html',{'cart':cart,'total':total})
@login_required()
def add_to_cart(request,b):
    b=Product.objects.get(id=b)
    user=request.user
    try:
        cart=Cart.objects.get(user=user,product=b)
        if(cart.quantity<cart.product.stock):
            cart.quantity+=1
            cart.save()
    except Cart.DoesNotExist:
        cart=Cart.objects.create(user=user,product=b,quantity=1)
        cart.save()

    return redirect('cart:cartview')
@login_required()
def cart_remove(request,b):
    b=Product.objects.get(id=b)
    user=request.user
    try:
        cart=Cart.objects.get(user=user,product=b)
        if(cart.quantity>1):
            cart.quantity-=1
            cart.save()
        else:
            cart.delete()
    except Cart.DoesNotExsist:
        pass
    return redirect('cart:cartview')
@login_required()
def cart_delete(request,b):
    b=Product.objects.get(id=b)
    user=request.user
    try:
        cart=Cart.objects.get(user=user,product=b)
        cart.delete()
    except Cart.DoesNotExsist:
        pass
    return redirect('cart:cartview')
@login_required()
def orderform(request):
    total=0
    if(request.method=="POST"):
        a = request.POST['a']
        p = request.POST['p']
        n = request.POST['n']
        user=request.user
        cart=Cart.objects.filter(user=user)
        for i in cart:
            total+=i.quantity*i.product.price
            ac=Account.objects.get(acctnumber=n)
            if(ac.amount>=total):
                ac.amount=ac.amount-total
                ac.save()
                for i in cart:
                    o=Order.objects.create(user=user,product=i.product,address=a,phone=p,order_status="paid",noofitems=i.quantity)
                    o.save()
                    i.product.stock=i.product.stock-i.quantity
                    i.product.save()
                    cart.delete()
                    msg="Order placed successfully"
                return render(request,'orderdetail.html',{'msg':msg})
            else:
                msg="Insufficient Amount.You cannot place the order"
                return render(request, 'orderdetail.html', {'msg': msg})

    return render(request,'orderform.html')
@login_required()
def orderview(request):
    u=request.user
    o=Order.objects.filter(user=u,order_status="paid")
    return render(request,'orderview.html',{'o':o,'u':u.username})

ecommerce/search/views.py
from django.shortcuts import render
from shop.models import Product
from django.db.models import Q
def searchresults(request):
    query=""
    products=None
    if(request.method=="POST"):
        query=request.POST['q']
        print(query)
        if(query):
            products=Product.objects.filter(Q(name__icontains=query)| Q(description__icontains=query))


    return render(request,'search.html',{'products':products,'query':query})

ecommerce/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=EB+Garamond&family=Lilita+One&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
<div class="container-fluid">
    <center>
        <img src="{% static 'images/logo.jpg' %}" height="100px" width="100px">
    </center>
</div>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">MY SHOP</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            SHOP
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item">All categories</a></li>
               <li><hr class="dropdown-divider"></li>
              {% for i in links  %}
            <li><a class="dropdown-item" href="{% url 'shop:allproducts' i.slug %}">{{i.name}}</a></li>
              {% endfor %}
          </ul>
        </li>
            {% if user.is_authenticated %}
          {% if user.username != 'admin' %}
          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'cart:cartview' %}"><i class="fa-solid fa-cart-shopping"></i>{{count}}</a>
        </li>
           <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'cart:orderview' %}">Your orders</a>
        </li>
          {% endif %}
          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:logout' %}">Logout</a>
        </li>
          {% else %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:register' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:login' %}">Login</a>
        </li>
        {% endif %}

      </ul>
      <form method="POST" class="d-flex" action="{% url 'search:searchresults' %}">
          {% csrf_token %}
        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
</div>
{% block content %}
{% endblock %}
<footer>
    <div class="footer">
        <p><i class="fa-solid fa-copyright"></i>My shop pvt lmt.All right reserved</p>
    </div>
</footer>

</body>
</html>

ecommerce/templates/cartview.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% if not cart %}
<div>
    <h1 class="text-center">Cart is empty</h1>
    <strong><a href="{% url 'shop:allprodcat' %}">Continue shopping</a></strong>
</div>
{% else %}
<div class="row">
    <h1 class="text-center">SHOPPING CART</h1>
    <div class="col-sm-7">
        <table class="table table-bordered">
            <tr>
                <th colspan="5">CART ITEMS</th>
            </tr>
            {% for i in cart %}
            <tr>
                <td><img src="{{i.product.image.url}}" height="100px" width="100px"</td>
                <td><p><strong>{{i.product.name}}</strong></p></td>
                <td><p><strong>Product Id:{{i.product.id}}</strong></p></td>
                <td><p><strong>Unit Price:{{i.product.price}}</strong></p></td>
                <td><p><strong>Quantity:{{i.quantity}}*{{i.product.price}}</strong></p></td>
                <td><p>subtotal:{{i.subtotal}}</p></td>
                <td>
                    {% if i.quantity < i.product.stock %}
                    <a href="{% url 'cart:add_to_cart' i.product.id %}"><i class="fa-solid fa-circle-plus"></i></a>
                    <a href="{% url 'cart:cart_remove' i.product.id %}"><i class="fa-solid fa-circle-minus"></i></a>
                    <a href="{% url 'cart:cart_delete' i.product.id %}"><i class="fa-solid fa-trash"></i></a>
                    {% else %}
                    <a href="{% url 'cart:cart_remove' i.product.id %}"><i class="fa-solid fa-circle-minus"></i></a>
                    <a href="{% url 'cart:cart_delete' i.product.id %}"><i class="fa-solid fa-trash"></i></a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
    <div class="col-sm-5">
     <table class="table table-bordered">
            <tr class="text-center">
                <th colspan="4">CHECK OUT</th>
            </tr>
         <tr class="text-center">
             <td>TOTAL AMOUNT:{{total}}</td>
         </tr>
        </table>
        <a href="{% url 'cart:orderform' %}"class="btn btn-primary">place order</a>
        <a href="{% url 'shop:allprodcat' %}" style="position:absolute;right:0;" class="btn btn-primary">Continue shopping</a>
</div>
</div>
{% endif %}
{% endblock %}

ecommerce/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
    <img src="{% static 'images/banner.avif' %}" height="450px" width="100%">
</div>
<div class="container-fluid mt-4" style="margin-bottom:100px;">
    <h3 class="text-center mb-2">Our Collections</h3>
    <p style="line-height:1.5;text-align:justify;">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum</p>
</div>
<div class="container-fluid mt-4" style="margin-bottom:100px;">
    <div class="row">
        {% for i in c %}
        <div class="col-sm-4">
            <div class="card" style="width: 24rem;">
  <img src="{{i.image.url}}" class="card-img-top" alt="..." style="height:200px;width:100%;">
  <div class="card-body">
    <h3 class="card-title text-center">{{i.name}}</h3>
    <p class="card-text" style="text-align:justify">{{i.description}}</p>
    <a href="{% url 'shop:allproducts' i.slug %}" style="position:relative;left:38%" class="btn btn-primary">PRODUCTS</a>
  </div>
</div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

ecommerce/templates/details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-4">
  <img src="{{b.image.url}}"  style="float:left;height:200px;width:100%;margin:150px;">
            </div>
<div class="col-md-8" style="padding:150px;">
  <div class="card-body">
    <h2 class="card-title">{{b.name}}</h2>
    <p class="card-text">{{b.price}}</p>
      <h4 class="card-text">Product description</h4>
      <p class="card-text" style="text-align:justify;">{{b.description}}</p>
      {% if user.username != 'admin' %}
      {% if b.stock <= 0 %}
      <h4>out of stock</h4>
      {% else %}
    <a href="{% url 'cart:add_to_cart' b.id %}" class="btn btn-primary">Add to cart</a>
      {% endif %}
      {% else %}
      {% if b.stock <= 0 %}
      <h4>Out of stock</h4>
      <a href="{% url 'admin:index' %}">ADD STOCK</a>

      {% endif %}
         {% endif %}
  </div>
</div>
        </div>
    </div>
{% endblock %}

ecommerce/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container" style="margin-bottom:100px;">
    <form method="POST" enctype="multipart/form-data">
     {% csrf_token %}
<form method="POST" class="border border-3 border primary">
    <div class="mb-3">
  <label  class="form-label">Username</label>
  <input type="text" class="form-control" name="u" placeholder="Enter username">
</div>
     <div class="mb-3">
  <label  class="form-label">password</label>
 <input type="password" class="form-control" name="p" placeholder="Enter password">
</div>
    <div class="mb-3">
        <input type="submit" value="Submit">
</div>
    </div>
{% if messages %}
{% for i in messages %}
<ul class="messages">
    <li>{{i}}</li>
</ul>
{% endfor %}
{% endif %}
</form>
{% endblock %}

ecommerce/templates/orderdetail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
 <h2 class="text-center text-success">{{msg}}</h2>
 <h5 class="text-center text-danger">Thank You...</h5>
 <p class="text-center"><a href="{% url 'shop:allprodcat' %}">Continue Shopping</a></p>
</div>
{% endblock %}

ecommerce/templates/orderform.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<form method="POST">
{% csrf_token %}
<div class="container">
<div class="mb-3">
  <label class="form-label">Address</label>
  <input type="text" class="form-control" name="a" placeholder="Enter Address">
</div>
<div class="mb-3">
  <label class="form-label">Phone</label>
  <input type="text" class="form-control" name="p" placeholder="Enter Phone">
</div>
<div class="mb-3">
  <label class="form-label">Accountno</label>
  <input type="text" class="form-control" name="n" placeholder="Enter Acctno">
</div>

<div class="mb-3">
    <input type="submit" class="btn btn-primary form-control">
</div>
</div></form>
{% endblock %}

ecommerce/templates/orderview.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
  <div class="row">
    <h5 class="text-center">Name of the customer::{{u}}</h5>
  {% for i in o %}
  <div class="col-sm-3 py-3" style="border:2px solid grey">
    <img src="{{i.product.image.url}}" height="150px" width="150px"></center>
  </div>
    <div class="col-sm-7 text-center" style="border:2px solid grey">
      Delivery Address:{{i.address}}</br>
      Phone Number :{{i.phone}}</br>
      {{i.product.name}}</br>
      {{i.product.price}}</br>
      Quantity Ordered:{{i.noofitems}}</br>
      Subtotal:{{i.subtotal}}</br>
      <strong class="text_primary">ordered on {{i.date_added}}</strong>
      <strong class="text_success">Delivery status {{i.delivery_status}}</strong>
    </div>
    {% endfor %}
</div>
</div>
{% endblock %}

ecommerce/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
    <img src="{{c.image.url}}" height="450px" width="100%">
</div>
<div class="container-fluid mt-4" style="margin-bottom:100px;">
    <h3 class="text-center mb-2">{{c.name}}</h3>
    <p style="line-height:1.5;text-align:justify;">{{c.description}}</p>
</div>
<div class="container-fluid mt-4" style="margin-bottom:100px;">
    <div class="row">
        {% for i in p %}
        <div class="col-sm-4">
            <div class="card" style="width: 26rem;">
  <img src="{{i.image.url}}" class="card-img-top" alt="..." style="height:200px;width:100%;">
  <div class="card-body">
    <h3 class="card-title text-center">{{i.name}}</h3>
      <h5 class="card-text text-center" style="text-align:justify">{{i.price}}</h5>
    <a href="{% url 'shop:details' i.slug %}" style="position:relative;left:38%" class="btn btn-primary">DETAILS</a>
  </div>
</div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

ecommerce/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container" style="margin-bottom:100px;">
    <form method="POST" enctype="multipart/form-data">
     {% csrf_token %}
<form method="POST" class="border border-3 border primary">
    <div class="mb-3">
  <label  class="form-label">Username</label>
  <input type="text" class="form-control" name="u" placeholder="Enter username">
</div>
<div class="mb-3">
  <label  class="form-label">Firstname</label>
 <input type="text" class="form-control" name="f" placeholder="Enter firstname">
</div>
    <div class="mb-3">
  <label  class="form-label">Lastname</label>
 <input type="text" class="form-control" name="l" placeholder="Enter lastname">
</div>
    <div class="mb-3">
  <label  class="form-label">email</label>
 <input type="email" class="form-control" name="e" placeholder="Enter email">
</div>
     <div class="mb-3">
  <label  class="form-label">password</label>
 <input type="password" class="form-control" name="p" placeholder="Enter password">
</div>
    <div class="mb-3">
  <label  class="form-label">confirm password</label>
 <input type="text" class="form-control" name="cp" placeholder="Confirm password">
</div>



    <div class="mb-3">
        <input type="submit" value="Register">
</div>
    </div>
</form>
{% endblock %}

ecommerce/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!--{{query}}-->
<!--{{products}}-->
<center>
    <h4>You have searched for <span class="text-success"> "{{query}}"</span></h4>
</center>

<div class="container-fluid mt-4" style="margin-bottom:100px;">
    <div class="row">
        {% for i in products %}
        <div class="col-sm-4">
            <div class="card" style="width: 26rem;">
  <img src="{{i.image.url}}" class="card-img-top" alt="..." style="height:200px;width:100%;">
  <div class="card-body">
    <h3 class="card-title text-center">{{i.name}}</h3>
      <h5 class="card-text text-center" style="text-align:justify">{{i.price}}</h5>
    <a href="{% url 'shop:details' i.slug %}" style="position:relative;left:38%" class="btn btn-primary">DETAILS</a>
  </div>
</div>
        </div>
        {% empty %}
        <h6 class="text-center text-dander">0 results found</h6>
        {% endfor %}
    </div>
</div>
{% endblock %}